apiVersion: apps/v1
kind: Deployment
metadata:
   name: test-deploy
   labels:
     app: connect-mysql
spec:
   selector:
     matchLabels:
       app: connect-mysql 
   replicas: 2
   strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 0
   template:
     metadata:
       labels:
         app: connect-mysql
     spec:
       containers:
       - name: connect-mysql
         image: ukml2019/mcd:latest
         imagePullPolicy: Always
         ports:
         - containerPort: 5000
       #resources:
       #  requests:
       #    memory: "64Mi"
       #    cpu: "50m"
       #  limits:
       #    memory: "256Mi"
       #    cpu: "500m"
           